default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: docker_app_development

test:
  <<: *default
  database: docker_app_test

production:
  <<: *default
  database: docker_app_production
